# Generated by Django 4.0 on 2022-01-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
