# Generated by Django 4.0 on 2022-01-31 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0004_delete_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 20, 28, 57, 329757)),
        ),
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 20, 28, 57, 329769)),
        ),
        migrations.AddField(
            model_name='note',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
