# Generated by Django 4.0 on 2022-01-31 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0005_note_created_note_deleted_note_modified_note_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 20, 29, 55, 699998)),
        ),
        migrations.AlterField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 20, 29, 55, 700011)),
        ),
    ]
